/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Transform `source` (the contents of `filename`) for use under a test runner. */
export declare function transform(source: string, filename: string, options?: TransformOptions | undefined | null): TransformOutput

/**
 * Options forwarded to the Rust transform. All fields are optional; omitted
 * fields fall back to the Rust-side [`NgOptions`] defaults.
 */
export interface TransformOptions {
  /**
   * `"auto"` (default), `"require"`, or `"import"`. Controls how `templateUrl`
   * is replaced. Unknown values fall back to `"auto"`.
   */
  importMode?: string
  /**
   * Whether the resolved module kind is ESM (used when `importMode` is
   * `"auto"`). Derived by the caller from tsconfig `module`.
   */
  esm?: boolean
  /** tsconfig `experimentalDecorators`. */
  experimentalDecorators?: boolean
  /** tsconfig `emitDecoratorMetadata`. */
  emitDecoratorMetadata?: boolean
  /** tsconfig `useDefineForClassFields` (default `false` — Angular's setting). */
  useDefineForClassFields?: boolean
  /**
   * Run the Angular JIT transforms (downlevel decorators + signal initializer
   * APIs). Default `true`.
   */
  jitTransforms?: boolean
  /**
   * ECMAScript target for syntax downleveling (e.g. `"es2017"`, `"esnext"`).
   * Derive from tsconfig `target`. Default `"esnext"`.
   */
  target?: string
  /**
   * Master switch for TS→JS + decorator lowering (default `true`; set `false`
   * only to inspect the pre-lowering TypeScript AST).
   */
  lower?: boolean
  /** Instrument the output for istanbul coverage in the same AST pass. */
  coverage?: boolean
  /** Global coverage variable name (default `"__coverage__"`). */
  coverageVariable?: string
  /** Emit a source map (default `true`). */
  sourceMap?: boolean
}

/** Result of a transform. */
export interface TransformOutput {
  /** Transformed (and optionally instrumented) JavaScript. */
  code: string
  /** Source map JSON, if requested. */
  map?: string
  /** Istanbul `FileCoverage` JSON, if `coverage` was set. */
  coverageMap?: string
  /** Non-fatal diagnostics. */
  errors: Array<string>
}
