/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Transform `source` (the contents of `filename`) for use under a test runner. */
export declare function transform(source: string, filename: string, options?: TransformOptions | undefined | null): TransformOutput

/**
 * Options forwarded to the Rust transform. All fields are optional; omitted
 * fields fall back to the Rust-side [`NgOptions`] defaults.
 */
export interface TransformOptions {
  /**
   * Output module format: `"commonjs"` (default) or `"esm"`. Drives both the
   * `templateUrl` replacement (`require` vs top-level `import`) and the
   * ESM→CommonJS rewrite. Unknown values fall back to `"commonjs"`. Derive it
   * from tsconfig `module`.
   */
  module?: string
  /** tsconfig `experimentalDecorators`. */
  experimentalDecorators?: boolean
  /** tsconfig `emitDecoratorMetadata`. */
  emitDecoratorMetadata?: boolean
  /** tsconfig `useDefineForClassFields` (default `false` — Angular's setting). */
  useDefineForClassFields?: boolean
  /**
   * Run the Angular JIT transforms (downlevel decorators + signal initializer
   * APIs). Default `true`.
   */
  jitTransforms?: boolean
  /**
   * Hoist `jest.mock()` / `jest.unmock()` / etc. above imports
   * (babel-plugin-jest-hoist). Default `false`; the jest plugin enables it.
   */
  hoistJestMock?: boolean
  /**
   * JSX runtime for `.tsx`/`.jsx` (mixed Angular + React): `"automatic"`
   * (default) or `"classic"`. Derive from tsconfig `jsx`.
   */
  jsx?: string
  /** Automatic-runtime import source (default `"react"`). tsconfig `jsxImportSource`. */
  jsxImportSource?: string
  /** Classic-runtime factory (default `"React.createElement"`). tsconfig `jsxFactory`. */
  jsxFactory?: string
  /**
   * Classic-runtime fragment factory (default `"React.Fragment"`).
   * tsconfig `jsxFragmentFactory`.
   */
  jsxFragmentFactory?: string
  /** `react-jsxdev`: emit JSX debug info (`__source`/`__self`). */
  jsxDevelopment?: boolean
  /**
   * ECMAScript target for syntax downleveling (e.g. `"es2017"`, `"esnext"`).
   * Derive from tsconfig `target`. Default `"esnext"`.
   */
  target?: string
  /**
   * Keep component styles instead of stripping them (default `false`).
   * `styleUrl`/`styleUrls` become default imports (`"esm"`) or `require(...)`
   * calls (`"commonjs"`), merged after any inline `styles` — the bundler's
   * CSS pipeline (e.g. vite + sass) compiles them. No CSS is compiled by the
   * transform itself. See `keepStylesQuery` for the query parameter that
   * makes the bundler return the CSS as a string.
   */
  keepStyles?: boolean
  /**
   * Query parameter appended to each style URL rewritten under `keepStyles`:
   * e.g. `"inline"` turns `./a.scss` into `./a.scss?inline` (`&inline` when
   * the URL already has a query), which makes vite return the compiled CSS
   * as a string. Default: unset — URLs are emitted verbatim. The vitest
   * plugin passes `"inline"`.
   */
  keepStylesQuery?: string
  /**
   * Master switch for TS→JS + decorator lowering (default `true`; set `false`
   * only to inspect the pre-lowering TypeScript AST).
   */
  lower?: boolean
  /** Instrument the output for istanbul coverage in the same AST pass. */
  coverage?: boolean
  /** Global coverage variable name (default `"__coverage__"`). */
  coverageVariable?: string
  /** Emit a source map (default `true`). */
  sourceMap?: boolean
}

/** Result of a transform. */
export interface TransformOutput {
  /** Transformed (and optionally instrumented) JavaScript. */
  code: string
  /** Source map JSON, if requested. */
  map?: string
  /** Istanbul `FileCoverage` JSON, if `coverage` was set. */
  coverageMap?: string
  /** Non-fatal diagnostics. */
  errors: Array<string>
}
